# 지도 학습과 비지도 학습 (머신러닝 알고리즘 분류)
#### 지도학습: 지도학습 알고리즘은 훈련하기 위한 데이터와 정답이 필요하다.
* 데이터와 정답을 **입력**과 **타깃**이라고 하고, 이 둘을 합쳐 **훈련 데이터**라고 부른다.

#### 비지도학습 : 비지도학습 알고리즘은 타깃 없이 입력 데이터만 사용한다.

# 훈련 세트와 테스트 세트
* 테스트 세트: 평가에 사용하는 데이터
* 훈련 세트: 훈련에 사용되는 데이터

In [1]:
fish_length = [25.4, 26.3, 26.5, 29.0, 29.0, 29.7, 29.7, 30.0, 30.0, 30.7, 31.0, 31.0, 
                31.5, 32.0, 32.0, 32.0, 33.0, 33.0, 33.5, 33.5, 34.0, 34.0, 34.5, 35.0, 
                35.0, 35.0, 35.0, 36.0, 36.0, 37.0, 38.5, 38.5, 39.5, 41.0, 41.0, 9.8, 
                10.5, 10.6, 11.0, 11.2, 11.3, 11.8, 11.8, 12.0, 12.2, 12.4, 13.0, 14.3, 15.0]
fish_weight = [242.0, 290.0, 340.0, 363.0, 430.0, 450.0, 500.0, 390.0, 450.0, 500.0, 475.0, 500.0, 
                500.0, 340.0, 600.0, 600.0, 700.0, 700.0, 610.0, 650.0, 575.0, 685.0, 620.0, 680.0, 
                700.0, 725.0, 720.0, 714.0, 850.0, 1000.0, 920.0, 955.0, 925.0, 975.0, 950.0, 6.7, 
                7.5, 7.0, 9.7, 9.8, 8.7, 10.0, 9.9, 9.8, 12.2, 13.4, 12.2, 19.7, 19.9]

In [2]:
fish_data = [[l, w] for l, w in zip(fish_length, fish_weight)]
fish_target = [1] * 35 + [0] * 14

In [30]:
fish_data[:10]

[[25.4, 242.0],
 [26.3, 290.0],
 [26.5, 340.0],
 [29.0, 363.0],
 [29.0, 430.0],
 [29.7, 450.0],
 [29.7, 500.0],
 [30.0, 390.0],
 [30.0, 450.0],
 [30.7, 500.0]]

In [31]:
fish_target[:10]

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

* 하나의  생선 데이터를 샘플이라고 부른다
* 도미와 빙어는 각각 35마리, 14마리가 있으므로 전체 데이터는 49개의 샘플이 있다
* 처음 35개를 훈련 세트로, 나머지 14개를 테스트 세트로 사용해보자

In [3]:
from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier()

In [4]:
print(fish_data[4])

[29.0, 430.0]


In [5]:
print(fish_data[0:5])

[[25.4, 242.0], [26.3, 290.0], [26.5, 340.0], [29.0, 363.0], [29.0, 430.0]]


In [6]:
print(fish_data[:5])

[[25.4, 242.0], [26.3, 290.0], [26.5, 340.0], [29.0, 363.0], [29.0, 430.0]]


In [7]:
print(fish_data[44:])

[[12.2, 12.2], [12.4, 13.4], [13.0, 12.2], [14.3, 19.7], [15.0, 19.9]]


In [12]:
# 훈련 세트로 입력값 중 0부터 34번째 인덱스까지 사용
train_input = fish_data[:35]

# 훈련 세트로 타깃값 중 0부터 34번째 인덱스까지 사용
train_target = fish_target[:35]

# 테스트 세트로 입력값 중 35번째부터 마지막 인덱스까지 사용
test_input = fish_data[35:]

# 테스트 세트로 타깃값 중 35번째부터 마지막 인덱스까지 사용
test_target = fish_target[35:]

In [13]:
# 정확도 0...
kn.fit(train_input, train_target)
kn.score(test_input, test_target)

0.0

# 샘플링 편향
* 훈련 세트와 테스트 세트에 샘플이 골고루 섞여 있지 않아 샘플링이 한쪽으로 치우치는 것
* 위 코드에서, 훈련 세트에 도미만 있기 때문에 테스트 세트가 무엇이든 무조건 도미라고 분류한다.
* 그러나 테스트 세트는 빙어만 있기 때문에 정답을 하나도 맞추지 못한다.

#### 훈련 세트와 테스트 세트를 나누기 전에 데이터를 섞든지, 골고루 샘플을 뽑아서 훈련 세트와 테스트 세트를 만들어야 한다.

# 넘파이
* 파이썬의 대표적인 배열 라이브러리
* 고차원의 배열을 손쉽게 만들고조작할 수 있는 간편한 도구를 많이 제공한다

In [14]:
import numpy as np

In [15]:
input_arr = np.array(fish_data)
target_arr = np.array(fish_target)

In [16]:
print(input_arr)

[[  25.4  242. ]
 [  26.3  290. ]
 [  26.5  340. ]
 [  29.   363. ]
 [  29.   430. ]
 [  29.7  450. ]
 [  29.7  500. ]
 [  30.   390. ]
 [  30.   450. ]
 [  30.7  500. ]
 [  31.   475. ]
 [  31.   500. ]
 [  31.5  500. ]
 [  32.   340. ]
 [  32.   600. ]
 [  32.   600. ]
 [  33.   700. ]
 [  33.   700. ]
 [  33.5  610. ]
 [  33.5  650. ]
 [  34.   575. ]
 [  34.   685. ]
 [  34.5  620. ]
 [  35.   680. ]
 [  35.   700. ]
 [  35.   725. ]
 [  35.   720. ]
 [  36.   714. ]
 [  36.   850. ]
 [  37.  1000. ]
 [  38.5  920. ]
 [  38.5  955. ]
 [  39.5  925. ]
 [  41.   975. ]
 [  41.   950. ]
 [   9.8    6.7]
 [  10.5    7.5]
 [  10.6    7. ]
 [  11.     9.7]
 [  11.2    9.8]
 [  11.3    8.7]
 [  11.8   10. ]
 [  11.8    9.9]
 [  12.     9.8]
 [  12.2   12.2]
 [  12.4   13.4]
 [  13.    12.2]
 [  14.3   19.7]
 [  15.    19.9]]


In [17]:
# (샘플 수, 특성 수)

print(input_arr.shape)

(49, 2)


### 타깃이 샘플과 함께 이동하지 않으면 올바르게 훈련될 수 없다.
* input_arr의 두 번째 값은 훈련 세트로 가고, target_arr의 두 번째 값은 테스트 세트로 가면 안 됨
* 인덱스 값을 통해, 이러한 문제를 막을 수 있다

In [21]:
# arange: 0에서 n-1까지 1씩 증가하는 인덱스를 만들 수 있음
np.random.seed(42)
index = np.arange(49)
np.random.shuffle(index)

In [26]:
index

array([13, 45, 47, 44, 17, 27, 26, 25, 31, 19, 12,  4, 34,  8,  3,  6, 40,
       41, 46, 15,  9, 16, 24, 33, 30,  0, 43, 32,  5, 29, 11, 36,  1, 21,
        2, 37, 35, 23, 39, 10, 22, 18, 48, 20,  7, 42, 14, 28, 38])

In [22]:
print(index)

[13 45 47 44 17 27 26 25 31 19 12  4 34  8  3  6 40 41 46 15  9 16 24 33
 30  0 43 32  5 29 11 36  1 21  2 37 35 23 39 10 22 18 48 20  7 42 14 28
 38]


In [23]:
# 배열 인덱싱
print(input_arr[[1,3]])

[[ 26.3 290. ]
 [ 29.  363. ]]


In [39]:
input_arr[index][:10]

array([[ 32. , 340. ],
       [ 12.4,  13.4],
       [ 14.3,  19.7],
       [ 12.2,  12.2],
       [ 33. , 700. ],
       [ 36. , 714. ],
       [ 35. , 720. ],
       [ 35. , 725. ],
       [ 38.5, 955. ],
       [ 33.5, 650. ]])

In [40]:
target_arr[index][:10]

array([1, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [32]:
# 변수 index에는 랜덤한 인덱스 값이 할당되어 있다.
# 입력, 타깃 데이터에 index 변수의 랜덤하게 섞인 인덱스를 할당한다.

train_input = input_arr[index[:35]]
train_target = target_arr[index[:35]]

만들어진 index의 첫 번째 값은 **13**이다.
* 따라서 train_input의 첫 번째 원소는 input_arr의 열네 번째 원소가 들어 있을 것이다.

In [25]:
print(input_arr[13], train_input[0])

[ 32. 340.] [ 32. 340.]


In [42]:
print(target_arr[13], train_target[0])

1 1
